### ISSUE TITLE
Publishing to Github

### ISSUE THREAD

**Issue by boldijar** [DrakeLeung/hexo-theme-again#2]
How can I publish with github?
This is my repo https://github.com/BoldijarPaul/boldijarpaul.github.io

But I get

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

How can I Fix this?

Thanks.

**Comment by lyyourc** [comment]
According to the [doc - deploy](https://hexo.io/docs/deployment.html#Git), you need to:
1. `npm install hexo-deployer-git --save`
2. Edit the `_config.yml`:
   
   ```
   deploy:
   type: git
   repo: <repository url>
   branch: [branch]
   message: [message]
   ```
3. [deploy](https://hexo.io/docs/generating.html#Deploy_After_Generating):
   
   ```
   hexo d -g
   ```
