### ISSUE TITLE
如何调整分页参数

### ISSUE THREAD

**Issue by Archmee** [DrakeLeung/hexo-theme-again#5]
问题如题，要如何修改配置文件使其主页分页的条数和archive分页的条数不一样，比如主页文章我想5条分成一页，但是archive下面我想分成10条一页或者不分页，该如何改，thx！

还有，其实我建议主题作者能对主题配置文件参数稍微介绍一下 😊

**Comment by lyyourc** [comment]
据我所知的话，需要修改根目录下面的 `_config.yml` 。

``` yml
# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# per page for different page
archive_generator:
  per_page: 7
  yearly: true
  monthly: true
```

如果不行的话，也许你需要安装一些依赖，比如：

``` bash
npm i --save hexo-generator-archive
```

如果还是不行的话，可以看我 [blog](https://github.com/DrakeLeung/blog) 源码或者 google 哦。
